name: SingleStore and GitHub Actions demo
on: push

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:10.18-jessie

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      singlestore:
        image: singlestore/cluster-in-a-box:latest
        volumes:
          - /var/lib/memsql
          - ./init.sql:/init.sql
        ports:
          - 3306:3306
          - 8080:8080
        environment:
          LICENSE_KEY: ${SINGLESTORE_LICENSE}
          ROOT_PASSWORD: "root"
          START_AFTER_INIT: "Y"

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Install dependencies
        run: npm ci

      - name: Connect to SingleStore
        # Runs a script that creates a SingleStore table, populates
        # the table with data, and then retrieves the data.
        run: node client.js
        # Environment variables used by the `client.js` script to create a new SingleStore table.
        env:
          # The hostname used to communicate with the SingleStore service container
          POSTGRES_HOST: postgres
          # The default SingleStore port
          POSTGRES_PORT: 5432